config/routes.rb
Rails.application.routes.draw do
  devise_scope :users do
    get "/users/sing_out" => "devise/sessions#destroy"
    get "/users/edit" => "devise/registrations#edit"
  end
  devise_for :users

  resources :items do
    get :upvote,    on: :member
    get :expensive, on: :collection
  end
  get "admin/users_count" => "admin#users_count"

  get ':controller(/:action(/:id))(.:format)'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many                :positions
	belongs_to              :user
	has_many :items, through: :positions
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commentable, polymorphic: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :price, numericality: { greater_than: 0, allow_nil: true }
	validates :name, presence: true

	has_many :positions
	has_many :carts, through: :positions
	has_many :comments, as: :commentable
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	
end

app/models/position.rb
class Position < ActiveRecord::Base
	belongs_to :item
	belongs_to :cart
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one  :cart
	has_many :orders
	has_many :comments
	has_many :blog_post
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :check_if_admin
	def user_count
		@users_count = User.count
		render layout: "admin"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
  
  private
	  def render_403
	  	render file: "public/403.html", status: 403
	  end

	  def render_404
	  	render file: "public/404.html", status: 404
	  end

	  def check_if_admin
	  	# render text: "Access denied", status: 403 unless params[:admin]
	  	# render_403 unless params[:admin]
	  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_filter :find_item,       only: [:show, :edit, :update, :destroy, :upvote]
	before_filter :check_if_admin,	only: [:create, :new, :edit, :update, :destroy]

	def index
		@items = Item.where(price: 18000)
	end

	def show
		unless @item
			render text: "Page No Found", status: 404
		end
	end

	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

	def create
		@item = Item.new(item_params)
		# В данном случае :item это вложенный хэш с параметрами	
		if @item.valid?
			@item.save
			redirect_to item_path(@item)
		else
			render "new"
		end
	end

	def update
		@item.update_attributes(item_params)
		if @item.errors.empty?
			redirect_to item_path(@item)
		else
			render "edit"
		end
	end

	def expensive
		@items = Item.where("price > 1000")
		render "index"
	end

	def destroy
		@item.destroy
		redirect_to action: "index"
	end

	def upvote
		@item.increment!(:votes_count)
		redirect_to action: :index
	end
	private

		def item_params
			params.require(:item).permit(:name, :price, :description, :weight)
		end

		def find_item
			@item = Item.where(id: params[:id]).first
			render_404 unless @item
		end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def urls_to_images(s)
		s.gsub! /(http:\/\/.*?\.(jpg|png))/, '<p><img src="\1"/></p>'
		s.html_safe
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %> on the site

app/views/items/_form.html.erb
<p>Название<br><%= f.text_field :name %></p>
<p>Описание<br><%= f.text_field :description %></p>
<p>Цена<br><%= f.text_field :price %></p>
<p>Ширина<br><%= f.text_field :weight %></p>

app/views/items/edit.html.erb
<h1>Update item</h1>
<%= form_for @item do |f| %>
		<p>Название<br><%= f.text_field :name %></p>
		<p>Описание<br><%= f.text_field :description %></p>
		<p>Цена<br><%= f.text_field :price %></p>
		<p>Площадь<br><%= f.text_field :weight %></p>
		<p><br><%= f.submit "Создать Объект" %></p>
<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
	<b>No items in store</b>
<% else	%>
	<table>
		<tr>
			<th>id</th>
			<th>Name</th>
			<th>Price</th>
			<th>Description</th>
			<th></th>
			<th></th>
		</tr>

		<% @items.each do |i| %>
		<tr>
			<td> <%= i.id %> </td>
			<td> <%= link_to i.name, item_path(i) %> </td>
			<td> <%= i.price %> </td>
			<td> <%= i.description %> </td>
			<td> <%= link_to "delete", i, method: :delete, data: { confirm: "do you want delete this Item ?"} %></td>
			<td> <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %> </td>
		</tr>
		<% end %>
	</table>
<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>
<%= form_for @item do |f| %>
	<p>Название<br><%= f.text_field :name %></p>
	<p>Описание<br><%= f.text_field :description %></p>
	<p>Цена<br><%= f.text_field :price %></p>
	<p>Площадь<br><%= f.text_field :weight %></p>
	<p><br><%= f.submit "Создать Объект" %></p>
<% end %>
<%= render partial: "shared/email" %>

app/views/items/show.html.erb
<h1><%=	@item.name %></h1>

<ul>
	<li><%=	@item.price %>.руб</li>
	<li><%=	urls_to_images(@item.description) %></li>
	<li><%=	@item.weight %>.кг</li>
	<li><%=	@item.weight %>.кг</li>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
	    <title>MyStore</title>
	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	    <%= csrf_meta_tags %>
	</head>
	<body>
	<div class="adminPanel">
		ADMIN
	</div>
	<div class="sessionInfo">
		<% if current_user %>
			<%= current_user.login %> | <% link_to "Sing out", destroy_user_session_path %>
		<% else %>
			<%= link_to "Sing in", new_user_registration_path %> | <%= link_to "Registration", new_user_registration_path %>
		<% end %>
	</div>
	<%= yield %>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	    <title>MyStore</title>
	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	    <%= csrf_meta_tags %>
	</head>
	
	<body>
		<div class="sessionInfo">
			<% if current_user %>
				<%= current_user.login %> | <%= link_to "Sing out", users_sing_out_path %>
			<% else %>
				<%= link_to "Sing in", new_user_session_path %> | <%= link_to "Registration", new_user_registration_path %>
			<% end %>
		</div>
		<%= yield %>
	</body>
</html>

app/views/shared/_email.html.erb
<div class="email">

  По всем вопросам обращайтесь на
  <script type="text/javascript"><!--
    var aixccwp = ["l", "@", "m", "g", "a", "p", "=", "@", "<", "h", "<", "s", "g", "a", "p", "\"", "l", "h", "e", "s", "k", "m", "i", "i", "i", "m", "k", ">", "r", "r", "\"", "s", "a", ".", " ", "o", "a", "o", "r", "a", "a", "t", ":", "s", "a", "o", "u", "m", "c", "m", ">", "a", "a", ".", ".", ".", "f", "h", "/", "u", "c", "l"];
    var fsklvjp = [31, 26, 57, 49, 47, 24, 7, 48, 58, 41, 0, 40, 27, 1, 46, 8, 53, 19, 5, 38, 42, 9, 30, 11, 52, 50, 20, 61, 44, 4, 36, 16, 10, 32, 2, 34, 60, 14, 22, 43, 51, 13, 15, 18, 25, 56, 23, 35, 33, 28, 37, 29, 21, 39, 54, 17, 6, 3, 59, 45, 55, 12];
    var lqnbuaw = new Array();
    for(var i=0; i<fsklvjp.length; i++){ lqnbuaw[fsklvjp[i]] = aixccwp[i]; }
    for(var i=0; i<lqnbuaw.length; i++){ document.write(lqnbuaw[i]); }
  // --></script>
  
  <noscript> Please enable Javascript to see the email address
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>